In [56]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from pltpow_analysis import *

Starting with HighMedium. Catergories for epc at (22,25], (25, 30], (30,38], (38,infty)

In [7]:
print(get_rmodel('HighMedium_polt_pow_easy.csv', 39, 10000, 0,6))
print(get_rmodel('HighMedium_polt_pow_easy.csv', 39, 10000, 7,11))

(array([-0.02]), 0.23, 0.011901397629172724, 0.0006476736162797385, 0.7161014898059577)
(array([-0.01]), 0.17, 0.007947431591293831, 8.725497142519234e-05, 0.697608997773304)


In [8]:
print(get_rmodel('HighMedium_polt_pow_easy.csv', 31, 38, 0,8))

(array([-0.02]), 0.22, 0.006452072312693501, 5.739281436476946e-05, 0.9784075502419205)


In [9]:
print(get_rmodel('HighMedium_polt_pow_easy.csv', 26, 30, 0,9))

(array([-0.02]), 0.22, 0.01063783552857143, 0.00016619549384248487, 0.9504331787635113)


In [10]:
print(get_rmodel('HighMedium_polt_pow_easy.csv', 23, 25, 0,9))

(array([-0.02]), 0.22, 0.010973652311926606, 0.00015821793842048698, 0.9571000624732646)


Now Medium

In [11]:
print(get_rmodel('Medium_polt_pow_easy.csv', 39 ,1000,0,8))

(array([-0.02]), 0.22, 0.009574197860962568, 0.00023524665775401073, 0.898564998393836)


In [12]:
print(get_rmodel('Medium_polt_pow_easy.csv', 31 ,38,0,8))

(array([-0.02]), 0.21, 0.006888888888888892, 7.899382716049392e-05, 0.972271715610171)


In [16]:
print(get_rmodel('Medium_polt_pow_easy.csv', 26 ,30,0,6))
print(get_rmodel('Medium_polt_pow_easy.csv', 26 ,30,7,11))

(array([-0.03]), 0.23, 0.011591836734693866, 0.00026269387755102, 0.9011812324990633)
(array([-0.01]), 0.11, 0.03416049382716049, 0.0012002592592592594, -24.40028448676266)


Now MediumLow

In [17]:
print(get_rmodel('MediumLow_polt_pow_easy.csv', 38, 1000, 0,8))

(array([-0.02]), 0.22, 0.01212765953519164, 0.0009525174995821291, 0.7418750087431898)


In [18]:
print(get_rmodel('MediumLow_polt_pow_easy.csv', 30, 38, 0,8))

(array([-0.02]), 0.21, 0.00904610365311653, 0.00011562468448512226, 0.9631265507289585)


In [23]:
print(get_rmodel('MediumLow_polt_pow_easy.csv', 26, 30, 0,6))

(array([-0.03]), 0.27, 0.047716780009009016, 0.0036695621351362203, 0.5516083045377576)


In [ ]:
print(get_rmodel('MediumLow_polt_pow_easy.csv', 22, 25, 0,8))

Below is the output that i think is the best presentable format. It's all files for distance [0,6] and [7,11] under the epc ranges that we've been using.

In [57]:
files = ['High_polt_pow_easy.csv', 'HighMedium_polt_pow_easy.csv', 'Medium_polt_pow_easy.csv', 'MediumLow_polt_pow_easy.csv', 'Low_polt_pow_easy.csv', 'LowRollish_polt_pow_easy.csv', 'Rollish_polt_pow_easy.csv']
ranges = [[22, 25], [26,30], [31, 38], [39, 1000]]

for file in files:
    print('On file:', file,'\n')
    for range in ranges:
        try:
            rmodel1 = get_rmodel(file, range[0], range[1], 0, 6)
            rmodel2 = get_rmodel(file, range[0], range[1], 7, 11)
        except:
            print('Invalid Range:', range)
        print('On range', str(range)+':', '0-6 mdoel is:', rmodel1, 'and 7-11 model is:', rmodel2)
    print('\n')

"""output:
On file: High_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.02]), 0.24, 0.016622605277108425, 0.00035904827859845615, 0.8525340677288574) and 7-11 model is: (array([-0.01]), 0.15, 0.0049377601428571465, 4.2455013007756316e-05, 0.7522983694794813)
On range [26, 30]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.011831245757575767, 0.00018702230038877666, 0.9169923602094903) and 7-11 model is: (array([-0.01]), 0.15, 0.006490134785714292, 6.0331181227222284e-05, 0.6659807107078892)
On range [31, 38]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.007793051300000008, 8.378667380469776e-05, 0.9531175693459203) and 7-11 model is: (array([-0.01]), 0.16, 0.002950940947368421, 1.4043997662424281e-05, 0.9298188037854836)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.008120833707078312, 0.00013636003078252597, 0.8884371779307725) and 7-11 model is: (array([-0.01]), 0.18, 0.008125920722572507, 9.72718881609219e-05, 0.6568223509237833)


On file: HighMedium_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018015540436363622, 0.000497141591816156, 0.8116875877537616) and 7-11 model is: (array([-0.01]), 0.12, 0.026340863534482766, 0.0007488336516317346, -6.227398435372551)
On range [26, 30]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.017148575782312936, 0.00036247576669798956, 0.8497922922471203) and 7-11 model is: (array([-0.01]), 0.12, 0.02985276032967034, 0.0009301547223882208, -7.823323116028556)
On range [31, 38]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.006143893681274901, 5.13720565692953e-05, 0.9739594182537231) and 7-11 model is: (array([-0.01]), 0.14, 0.014000118936416173, 0.000215559741951149, -0.5667582367309167)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.011901397629172724, 0.0006476736162797385, 0.7161014898059577) and 7-11 model is: (array([-0.01]), 0.17, 0.007947431591293831, 8.725497142519234e-05, 0.697608997773304)


On file: Medium_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.012102040816326518, 0.0002545918367346935, 0.9124570054373972) and 7-11 model is: (array([-0.]), 0.1, 0.041488372093023265, 0.0017505116279069772, -58.894448556624695)
On range [26, 30]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.011591836734693866, 0.00026269387755102, 0.9011812324990633) and 7-11 model is: (array([-0.01]), 0.11, 0.03416049382716049, 0.0012002592592592594, -24.40028448676266)
On range [31, 38]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.011309523809523813, 0.00015409523809523817, 0.9281516706433505) and 7-11 model is: (array([-0.01]), 0.11, 0.03824844720496894, 0.001499664596273292, -19.485226090613317)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.006819256756756758, 0.0001616131756756757, 0.9067723296529475) and 7-11 model is: (array([-0.01]), 0.16, 0.009063389391979301, 0.00011956274256144889, 0.5260215489267527)


On file: MediumLow_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.03]), 0.24, 0.016134348258426967, 0.000408650539314595, 0.8878015576148761) and 7-11 model is: (array([-0.]), 0.1, 0.036667402142857144, 0.0014523591097713592, -12.465133339857617)
On range [26, 30]: 0-6 mdoel is: (array([-0.03]), 0.27, 0.047716780009009016, 0.0036695621351362203, 0.5516083045377576) and 7-11 model is: (array([-0.01]), 0.14, 0.02074374725316455, 0.000655524713328184, -0.37215524517640675)
On range [31, 38]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.015841903503968257, 0.00030690866567574846, 0.8722025936688609) and 7-11 model is: (array([-0.]), 0.09, 0.032164324513698626, 0.0010670045128311095, -31.870614364605423)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.018066806337251367, 0.001210716091179169, 0.632624480481252) and 7-11 model is: (array([-0.01]), 0.15, 0.011638641505882358, 0.0001901176387900871, 0.1542985509731254)


On file: Low_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.012288925168421047, 0.00023250362007149792, 0.9402330711759828) and 7-11 model is: (array([-0.]), 0.08, 0.022378198275, 0.0005192782336622062, -27.077478060762452)
On range [26, 30]: 0-6 mdoel is: (array([-0.03]), 0.29, 0.05772173648863637, 0.004679881167000922, 0.526966027598095) and 7-11 model is: (array([-0.01]), 0.18, 0.0337340312368421, 0.0013520650487016958, -0.8632269292204959)
On range [31, 38]: 0-6 mdoel is: (array([-0.03]), 0.22, 0.013659005238095235, 0.0003173514968633059, 0.8771525169445765) and 7-11 model is: (array([-0.]), 0.08, 0.022826932790476193, 0.0005453720018295491, -21.440391435319643)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.010803546462669686, 0.0002538975382300265, 0.8866862173887355) and 7-11 model is: (array([-0.01]), 0.13, 0.02448195926325411, 0.0006951424951570933, -3.3486885177881422)


On file: LowRollish_polt_pow_easy.csv 

Invalid Range
On range [22, 25]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.010803546462669686, 0.0002538975382300265, 0.8866862173887355) and 7-11 model is: (array([-0.01]), 0.13, 0.02448195926325411, 0.0006951424951570933, -3.3486885177881422)
On range [26, 30]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.012880794904761905, 0.0002432817695629369, 0.9337308845698763) and 7-11 model is: (array([-0.01]), 0.09, 0.038983183500000004, 0.0015343005530099947, -98.35173913513565)
On range [31, 38]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.024060299564356433, 0.001551892875644051, 0.6469347112017487) and 7-11 model is: (array([-0.]), 0.09, 0.029037208161764708, 0.0009804391126459267, -2.342069329994416)
On range [39, 1000]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018859381275905116, 0.0013530308722487071, 0.6524694638046387) and 7-11 model is: (array([-0.01]), 0.12, 0.023700384862179492, 0.0006309910140180345, -5.0250785543794985)


On file: Rollish_polt_pow_easy.csv 

Invalid Range
On range [22, 25]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018859381275905116, 0.0013530308722487071, 0.6524694638046387) and 7-11 model is: (array([-0.01]), 0.12, 0.023700384862179492, 0.0006309910140180345, -5.0250785543794985)
Invalid Range
On range [26, 30]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018859381275905116, 0.0013530308722487071, 0.6524694638046387) and 7-11 model is: (array([-0.01]), 0.12, 0.023700384862179492, 0.0006309910140180345, -5.0250785543794985)
Invalid Range
On range [31, 38]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018859381275905116, 0.0013530308722487071, 0.6524694638046387) and 7-11 model is: (array([-0.01]), 0.12, 0.023700384862179492, 0.0006309910140180345, -5.0250785543794985)
Invalid Range
On range [39, 1000]: 0-6 mdoel is: (array([-0.03]), 0.23, 0.018859381275905116, 0.0013530308722487071, 0.6524694638046387) and 7-11 model is: (array([-0.01]), 0.12, 0.023700384862179492, 0.0006309910140180345, -5.0250785543794985)
"""

On file: High_polt_pow_easy.csv 

On range [22, 25]: 0-6 mdoel is: (array([-0.02]), 0.24, 0.016622605277108425, 0.00035904827859845615, 0.8525340677288574) and 7-11 model is: (array([-0.01]), 0.15, 0.0049377601428571465, 4.2455013007756316e-05, 0.7522983694794813)
On range [26, 30]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.011831245757575767, 0.00018702230038877666, 0.9169923602094903) and 7-11 model is: (array([-0.01]), 0.15, 0.006490134785714292, 6.0331181227222284e-05, 0.6659807107078892)
On range [31, 38]: 0-6 mdoel is: (array([-0.02]), 0.23, 0.007793051300000008, 8.378667380469776e-05, 0.9531175693459203) and 7-11 model is: (array([-0.01]), 0.16, 0.002950940947368421, 1.4043997662424281e-05, 0.9298188037854836)
On range [39, 1000]: 0-6 mdoel is: (array([-0.02]), 0.22, 0.008120833707078312, 0.00013636003078252597, 0.8884371779307725) and 7-11 model is: (array([-0.01]), 0.18, 0.008125920722572507, 9.72718881609219e-05, 0.6568223509237833)


On file: HighMedium_polt_pow_easy.csv 

On r